//{{NO_DEPENDENCIES}}
// Archivo de inclusión generado de Microsoft Visual C++.
// Usado por Proyecto ED.rc
//
#define IDCANCEL2                       4
#define IDOK2                           5
#define IDCANCEL3                       6
#define IDD_INICIO                      101
#define IDD_DIALOG1                     103
#define IDD_VentanaPrincipal            103
#define IDR_MENU1                       105
#define IDD_REGISTROPAC                 106
#define IDD_REGISTROCITAS               108
#define IDD_REGISTROmed                 110
#define IDD_REGISTROesp                 112
#define IDD_Consulta_ESPECIALIDADES     116
#define IDD_BUSCAR_Pacientes            118
#define IDD_Consulta_porsemana          120
#define IDD_ConsultaCITAS               122
#define IDD_CONSULTA_MedicoMes          124
#define IDD_Consulta_semana_especialidad 126
#define IDD_DIALOG2                     128
#define IDD_BUSCAR_medicos              128
#define ID_Ingresar                     1001
#define IDC_BUTTON2                     1002
#define IDD_SALIR                       1002
#define ID_Reporte_medicos              1002
#define IDD_lbNombre                    1003
#define IDD_Contra                      1004
#define IDC_IMAGEN                      1005
#define IDC_EDIT1                       1006
#define ID_Especialidad                 1006
#define IDC_COMBO1                      1007
#define IDC_EDIT2                       1008
#define IDC_EDIT3                       1009
#define IDC_COMBO4                      1009
#define IDC_REFERENCIA                  1009
#define IDC_COMBO_Paciente              1009
#define IDC_DATETIMEPICKER1             1010
#define IDC_COMBO9                      1010
#define IDC_Dia                         1010
#define IDC_COMBO2                      1011
#define IDC_EDIT4                       1012
#define IDC_COMBO5                      1012
#define IDC_EDAD                        1012
#define IDC_COMBO6                      1013
#define IDC_E3                          1013
#define IDC_COMBO7                      1014
#define IDC_E4                          1014
#define IDC_COMBO8                      1015
#define IDC_E5                          1015
#define IDC_DATETIMEPICKER2             1016
#define IDC_SALIDA1                     1016
#define IDC_Hora                        1016
#define IDC_SALIDA2                     1017
#define IDC_SALIDA3                     1018
#define IDC_CLAVE                       1019
#define IDC_SALIDA4                     1019
#define IDC_COMBO13                     1020
#define IDC_SALIDA5                     1020
#define IDC_EDIT5                       1026
#define IDC_NumCel                      1026
#define IDC_BUTTON1                     1027
#define IDC_E1                          1028
#define IDC_E2                          1029
#define IDC_RADIO1                      1030
#define IDC_RADIO2                      1031
#define IDC_RADIO3                      1032
#define IDC_RADIO4                      1033
#define IDC_RADIO5                      1034
#define IDC_Consultorio                 1035
#define NUMERO_CITA                     1036
#define ID_NUMERO_CITA                  1036
#define IDC_PACIENTE                    1038
#define IDC_GENERO                      1039
#define IDC_TELEFONO                    1040
#define IDC_FECHA_NACIMIENTO            1041
#define IDC_1er_medico                  1042
#define IDCANCEL_esp                    1043
#define IDC_Especialidad                1046
#define IDC_Doctor                      1047
#define IDC_Celular                     1048
#define IDC_Cedula                      1049
#define IDC_APELLIDOS                   1050
#define IDC_APPELIDOS                   1051
#define IDC_REPORTE                     1052
#define ID_REGISTRAR                    1053
#define IDC_Descripcion                 1054
#define IDC_DATETIMEPICKER3             1058
#define IDC_Hora2                       1058
#define IDC_FOTO                        1060
#define IDC_Foto_doc                    1061
#define IDC_actualizar                  1062
#define IDC_lista_nombres               1063
#define IDC_BUTTON3                     1065
#define IDC_CONFIRMAR                   1066
#define IDC_Nueva_especialidad          1067
#define IDC_descripcion_especialidad    1068
#define IDC_LIST1                       1071
#define IDC_SALIR                       1072
#define IDC_Estadodecita                1073
#define IDC_COMBO3                      1074
#define IDC_MOSTRAR_TODO                1075
#define IDC_ELIMINAR                    1076
#define IDC_ATENCION                    1077
#define ID_REGISTROS_REGISTROSDEESPECIALIDADES 40001
#define ID_REGISTROS_REGISTRODEMEDICOS  40002
#define ID_REGISTRODEMEDICOS_REPORTE    40003
#define ID_REGISTROS_REGISTRODECITAS    40004
#define ID_REGISTROS_REGISTRODEPACIENTES 40005
#define ID_REGISTRODEPACIENTES_REPORTE  40006
#define ID_CONSULTAS_CITAS              40007
#define ID_CONSULTASDECITAS_MES         40008
#define ID_CONSULTASDECITAS_SEMANA      40009
#define ID_CONSULTASDECITAS_PORESPECIALIDAD 40010
#define ID_SALIR                        40011
#define IDM_SALIR                       40012
#define IDR_PACIENTE                    40013
#define ID_REGISTROS_REGISTRODEMEDICOS40014 40014
#define ID_CONSULTAS_CITAS_MEDICOS      40015
#define ID_CONSULTASDECITAS_MEDICO      40016
#define ID_CONSULTASDECITAS_ESPECIALIDAD 40017
#define IDReg_PACIENTE                  40018
#define ID_PACIENTES_BUSCAR             40019
#define ID_CONSULTASporsemana_MEDICO    40020
#define ID_CONSULTASporsemana           40021
#define ID_CONSULTASDECITAS_PORESPECIALIDAD40022 40022
#define ID_CONSULTASDECITAS_medicomes   40023
#define ID_CONSULTASDECITAS_PORESPECIALIDADsemana 40024
#define ID_CONSULTASDECITAS_CITASENPANTALLA 40025
#define ID_DOCTORES_BUSCAR              40026

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         40027
#define _APS_NEXT_CONTROL_VALUE         1078
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
